// Generated by CoffeeScript 1.6.3
(function() {
  var User, async, mongoose, querystring, request;

  console.log("fire yummly!");

  User = require('../../models/lib/user');

  request = require('request');

  async = require('async');

  mongoose = require('mongoose');

  querystring = require('querystring');

  module.exports = function(req, res) {
    return res.render('share');
  };

}).call(this);
