// Generated by CoffeeScript 1.6.3
(function() {
  var Substitute, User, async, mongoose, querystring, request, _;

  console.log("fire yummly!");

  User = require('../../models/lib/user');

  request = require('request');

  async = require('async');

  mongoose = require('mongoose');

  querystring = require('querystring');

  _ = require('underscore');

  Substitute = require('./../../models/lib/mongodb.js').Substitute;

  console.log("Subsittute", Substitute);

  module.exports = function(io) {
    var share;
    io.sockets.on('connection', function(socket) {
      return socket.on('substitute-form', function(data) {
        var parsedData, substitute;
        parsedData = querystring.parse(data);
        substitute = new Substitute(parsedData);
        return substitute.save(function(err, data) {
          console.log("save");
          if (err) {
            return console.log(err);
          } else {
            return console.log("sent to database:", data);
          }
        });
      });
    });
    share = function(req, res) {
      return res.render('share');
    };
    return {
      share: share
    };
  };

}).call(this);
