// Generated by CoffeeScript 1.6.3
(function() {
  var Substitute, User, async, mongoose, querystring, request, _;

  console.log("fire substitution!");

  User = require('../../models/lib/user');

  request = require('request');

  async = require('async');

  mongoose = require('mongoose');

  querystring = require('querystring');

  _ = require('underscore');

  Substitute = require('./../../models/lib/mongodb.js').Substitute;

  module.exports = function(io) {
    var findSubstitutes, getSubObj, objectToRender;
    objectToRender = {
      q: "sdf"
    };
    getSubObj = function(substitutes) {
      var item, mappedQty, pluckedNonVeganItems, pluckedTwice, ratio, substitute, substituteArray, uniqueItems, uniqueUnits, _i, _len;
      substituteArray = [];
      for (_i = 0, _len = substitutes.length; _i < _len; _i++) {
        substitute = substitutes[_i];
        substitute['non-vegan-qty'];
        mappedQty = _.map(substitute['substitute-qty'], function(num) {
          if (typeof num === String) {
            return Number(num);
          }
        });
        ratio = _.map(mappedQty, function(num) {
          return num / substitute['non-vegan-qty'];
        });
        uniqueUnits = _.uniq(substitute['non-vegan-units']);
        item = {
          nonVegan: {
            item: substitute['non-vegan-item'],
            units: substitute['non-vegan-units'],
            qty: substitute['non-vegan-qty']
          },
          vegan: {
            items: substitute['vegan-substitute'],
            units: substitute['substitute-units'],
            qty: mappedQty,
            notes: substitute['substitute-description']
          },
          ratio: ratio
        };
        substituteArray.push(item);
      }
      pluckedNonVeganItems = _.pluck(substituteArray, 'nonVegan');
      pluckedTwice = _.pluck(pluckedNonVeganItems, 'item');
      uniqueItems = _.uniq(pluckedTwice);
      return {
        q: substituteArray,
        uniqueItems: uniqueItems
      };
    };
    findSubstitutes = function(callback) {
      return Substitute.find({}, function(err, substitutes) {
        if (err) {
          return console.log('ERROR');
        } else {
          return callback(getSubObj(substitutes));
        }
      });
    };
    io.sockets.on('connection', function(socket) {
      return socket.on('requestparams', function(dataFromClient) {
        var paramsForClient, val;
        console.log("HERRERERE");
        val = querystring.parse(dataFromClient);
        console.log("val::::", val);
        paramsForClient = {};
        if (val.item) {
          paramsForClient['non-vegan-item'] = val.item;
        }
        if (val.units) {
          paramsForClient['non-vegan-units'] = val.units;
        }
        if (val.qty) {
          paramsForClient['non-vegan-qty'] = val.qty;
        }
        return Substitute.find(paramsForClient, function(err, databaseItem) {
          socket.emit('sendparams', databaseItem);
          return console.log(databaseItem);
        });
      });
    });
    return {
      index: function(req, res) {
        return findSubstitutes(function(substitutionObject) {
          return res.render('substitution.jade', substitutionObject);
        });
      }
    };
  };

}).call(this);
