// Generated by CoffeeScript 1.6.3
(function() {
  var User, async, mongoose, request;

  console.log("fire yumRouter!");

  User = require('../../models/lib/user');

  console.log("fire yummly.js");

  request = require('request');

  async = require('async');

  mongoose = require('mongoose');

  module.exports = {
    index: require('./yummly'),
    yumyum: require('./yumControl')
  };

}).call(this);
