// Generated by CoffeeScript 1.6.3
(function() {
  var User, async, mongoose, request;

  console.log("fire yumRouter!");

  User = require('../../models/lib/user');

  request = require('request');

  async = require('async');

  mongoose = require('mongoose');

  module.exports = function(io) {
    console.log("yummly", require("./yummly"));
    return {
      yummly: require('./yummly')(io).yummly,
      substitution: require('./substitution')(io).index,
      share: require('./share')
    };
  };

}).call(this);
