// Generated by CoffeeScript 1.6.3
(function() {
  var LocalStrategy, User, passport;

  passport = require('passport');

  LocalStrategy = require('passport-local').Strategy;

  User = require('./../models/lib/user');

  passport.use(new LocalStrategy({
    usernameField: 'username'
  }, function(username, password, done) {
    console.log(username, password);
    User.authenticate(username, password, function(err, user, message) {
      return done(err, user, message);
    });
  }));

  passport.serializeUser(function(user, done) {
    done(null, user.id);
  });

  passport.deserializeUser(function(id, done) {
    User.findById(id, function(err, user) {
      done(err, user);
    });
  });

  module.exports = passport;

}).call(this);
