// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = {};

  config.name = 'Veganizzm.com';

  config.dbname = 'vegan-app';

  config.sessionSecret = 'myprecious';

  config.port = 1337;

  config.someAPIkey = 'asdfasdfaksafaasdfa';

  module.exports = config;

}).call(this);
