// Generated by CoffeeScript 1.6.3
(function() {
  var links;

  links = [
    {
      label: 'Recipes',
      key: 'yummly',
      path: '/yummly'
    }, {
      label: 'Substitutes',
      key: 'substitution',
      path: '/substitution'
    }, {
      label: 'Share',
      key: 'share',
      path: '/share'
    }
  ];

  module.exports = links;

}).call(this);
