// Generated by CoffeeScript 1.6.3
(function() {
  var links;

  links = [
    {
      label: 'Home',
      key: 'front',
      path: '/'
    }, {
      label: 'Profile',
      key: 'profile',
      path: '/profile'
    }, {
      label: 'About',
      key: 'about',
      path: '/about'
    }, {
      label: 'Recipes',
      key: 'yummly',
      path: '/yummly'
    }, {
      label: 'Substitutes',
      key: 'substitutes',
      path: '/substitutes'
    }, {
      label: 'Share',
      key: 'share',
      path: '/submitrecipe'
    }
  ];

  module.exports = links;

}).call(this);
