// Generated by CoffeeScript 1.6.3
(function() {
  var home, isAdmin, passport, request, restrict, yumRoute;

  passport = require('passport');

  home = require('./../routes/lib/home');

  yumRoute = require('./../routes/lib/yumRouter');

  request = require('request');

  restrict = function(req, res, next) {
    if (req.user) {
      next();
    } else {
      res.redirect('/login');
    }
  };

  isAdmin = function(req, res, next) {
    if (req.user.role === 'admin') {
      next();
    } else {
      res.redirect('/');
    }
  };

  module.exports = function(app, request) {
    app.get('/', home.index);
    app.get('/login', home.login);
    app.post('/login', passport.authenticate('local', {
      failureRedirect: '/login'
    }), function(req, res) {
      res.redirect('/');
    });
    app.get('/logout', restrict, home.logout);
    app.get('/about', home.about);
    app.get('/about/tos', home.tos);
    app.get('/register', home.getRegister);
    app.post('/register', home.postRegister);
    app.get('/checkExists', home.checkExists);
    app.get('/profile', restrict, home.profile);
    app.get('/veganizzm', home.requestVeganizzm);
    app.get('/yummly', yumRoute.yummly);
    app.get('/submitrecipe', yumRoute.yumControl);
    app.get('/substitutes', yumRoute.substitutes);
    return io.sockets.on('connection', yumRoute.yummly);
  };

}).call(this);
