// Generated by CoffeeScript 1.6.3
(function() {
  var home, isAdmin, passport, request, restrict;

  passport = require('passport');

  home = require('./../routes/lib/home');

  request = require('request');

  restrict = function(req, res, next) {
    if (req.user) {
      next();
    } else {
      res.redirect('/login');
    }
  };

  isAdmin = function(req, res, next) {
    if (req.user.role === 'admin') {
      next();
    } else {
      res.redirect('/');
    }
  };

  module.exports = function(app, request, io) {
    var yumRouter;
    yumRouter = require('./../routes/lib/yumRouter')(io);
    app.get('/', home.index);
    app.get('/login', home.login);
    app.post('/login', passport.authenticate('local', {
      failureRedirect: '/login'
    }), function(req, res) {
      res.redirect('/');
    });
    app.get('/logout', restrict, home.logout);
    app.get('/register', home.getRegister);
    app.post('/register', home.postRegister);
    app.get('/checkExists', home.checkExists);
    app.get('/profile', restrict, home.profile);
    app.get('/share', yumRouter.share);
    app.get('/yummly', yumRouter.yummly);
    return app.get('/substitution', yumRouter.substitution);
  };

}).call(this);
