// Generated by CoffeeScript 1.6.3
(function() {
  var mongoose;

  mongoose = require('mongoose');

  module.exports = {
    Substitute: mongoose.model('Substitute', {
      "non-vegan-item": String,
      "non-vegan-qty": Number,
      "non-vegan-units": String || Number,
      "vegan-substitute": Array || String,
      "substitute-qty": Array || Number,
      "substitute-units": Array || String || Number,
      "substitute-description": Array || String
    })
  };

}).call(this);
